- src/otoole/__init__.py
- src/otoole/preprocess/create_datapackage.py
- src/otoole/preprocess/datafile_to_datapackage.py
- src/otoole/preprocess/excel_to_osemosys.py
- src/otoole/preprocess/longify_data.py
- src/otoole/validate.py
- src/otoole/validate.yaml
- tests/test_validate.py
- Adds general functionality to enable validation of any naming convention
- Naming convention is described in a validation config file
- Functions return true/false depending on full match of name to convention
To do:
> Adds functions to perform pattern matching on technology, fuel and other codes

- CHANGELOG.rst
- README.rst
- docs/index.rst
- requirements.txt
- setup.cfg
- src/otoole/visualise/res.py
- tests/test_visualise.py
- tests/travis_install.sh
Fix for #8 and #15 
- Tidies up the documentation
- Prepares for release v0.4
> Remove pygraphviz

- src/otoole/preprocess/datapackage.json
FIX DATA TYPES for the parameters TradeRoute and TotalAnnualMinCapacity
> FIX DATA TYPES

- .pre-commit-config.yaml
- README.rst
- mypy.ini
- pyproject.toml
- requirements.txt
- setup.cfg
- src/otoole/__init__.py
- src/otoole/cli.py
- src/otoole/preprocess/__init__.py
- src/otoole/preprocess/create_datapackage.py
- src/otoole/preprocess/datapackage.json
- src/otoole/preprocess/narrow_to_datafile.py
- tests/preprocess/test_csv_to_file.py
- Fixes a bug introduced in 0.5.4 where sets were omitted from a datafile
- Adds a performance enhancement to reduce size of the model files, by omitting all values which match the default values.
> Fixes datafile writing bug

- CHANGELOG.rst
- README.rst
- requirements.txt
- setup.cfg
- src/otoole/cli.py
- src/otoole/preprocess/datafile_to_datapackage.py
- src/otoole/validate.py
- tests/preprocess/test_file2package.py
> Provide help to make validation easier to use

- CHANGELOG.rst
- src/otoole/cli.py
- src/otoole/preprocess/__init__.py
- src/otoole/preprocess/create_datapackage.py
- src/otoole/preprocess/excel_to_osemosys.py
- src/otoole/preprocess/longify_data.py
- src/otoole/preprocess/narrow_to_datafile.py
- tests/preprocess/test_csv_to_file.py
> Excel fix 51

- src/otoole/read_strategies.py
- tests/test_read_strategies.py
> Catch if parameter not in config

- setup.cfg
- src/otoole/results/convert.py
- tests/results/test_convert.py
> Fixes bug where otoole result processing causes duplicate index error in pandas dataframe

- src/otoole/write_strategies.py
> Fix extra lines on Windows

- docs/functionality.rst
- src/otoole/input.py
- src/otoole/preprocess/longify_data.py
> Small additions to documentation and usability

- setup.cfg
- src/otoole/input.py
- src/otoole/preprocess/config.yaml
- src/otoole/preprocess/datapackage.json
- src/otoole/read_strategies.py
- src/otoole/results/result_package.py
- src/otoole/results/results.py
- src/otoole/visualise/res.py
- tests/conftest.py
- tests/results/test_results_package.py
- tests/test_read_strategies.py
Fix for #86 
And #72:
The release of OSeMOSYS v1.0 adds a new parameter (`DiscountRateStorage`) and modifies the parameter `DiscountRate` to support technology-specific discount rates.
These require updates to the datapackage schema, default_values, config and results computation contained in this pull request.
> ReadStrategies cast dataframes to correct types

- CHANGELOG.rst
- docs/functionality.rst
- src/otoole/__init__.py
- src/otoole/cli.py
- src/otoole/results/results.py
- tests/test_read_strategies.py
**otoole** now supports processing of Gurobi solution files.
> Process Gurobi solution file

- src/otoole/cli.py
Fixed an issue where the datapackage functionality was not deprecated properly in the `results` functionality
> Fixed deprecation message

- .github/workflows/python.yaml
Added a GitHub action to push code coverage stats to coveralls.io
> Linked Coveralls 

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/docs.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
- .github/pull_request_template.md
Added three issue templates (bug reports, feature requests, doc updates) and one PR template
> Issue templates

- CHANGELOG.rst
- docs/contributing.rst
- docs/data.rst
- docs/examples.rst
- docs/functionality.rst
Updates to docs include: 
- Fixing typos/formatting 
- Adding install instructions for GLPK and CBC 
- Updating change log 
na
na
> Minor docs updates

- .github/workflows/python.yaml
- setup.cfg
- src/otoole/utils.py
Fixes issue with the latest version of pydantic which broke our validation code.
Pins pydantic to less than version 2.0
#185 
This has not been documented.
> Pin pydantic to less than v2

- docs/_static/validation-data.txt
- docs/conf.py
- docs/data.rst
- docs/examples-validation.rst
- docs/examples.rst
- docs/functionality.rst
This PR implements documentation updates following the feedback received from the [JOSS reviewers](https://github.com/openjournals/joss-reviews/issues/5511). 
- Added simple `data.txt` file for validation example 
- Moved solver installation to the start of the examples section
> Documentation Update

- CHANGELOG.rst
- docs/requirements.txt
- setup.cfg
Updates ChangeLog for release version `1.1.0`
na
na
> Release 1.1.0 Candidate 

- README.rst
Added joss status badge to readme
> Added joss status badge to readme

- CITATION.cff
Adds a preferred citation to the repository ready for when the JOSS paper is published.
> Modified citation file with template for JOSS article
