- README.rst
- src/otoole/cli.py
- src/otoole/visualise/__init__.py
- src/otoole/visualise/res.py
- Visualises a reference energy system using networkx, graphviz and dot.
- Very useful for debugging purposes e.g. note that the simplicity model shown below has no CO2 emission for Diesel imports, and several orphaned fuels, emissions and technologies.
To do:
> Visualise a reference energy system from a Tabular Data Package

- setup.cfg
- src/otoole/cli.py
- src/otoole/preprocess/__init__.py
- src/otoole/preprocess/datafile_to_datapackage.py
- src/otoole/preprocess/datapackage.json
- src/otoole/preprocess/excel_to_osemosys.py
- src/otoole/preprocess/longify_data.py
- tests/preprocess/test_file2package.py
Closes #5
Uses the PuLP.amply module to read in parameters and sets from an OSeMOSYS datafile, converts the data to narrow and well-formatted pandas DataFrames, and writes these out into a folder.
There are a number of outstanding issues with this approach:
- the amply module does not read in tabbing format tables from a datafile (see https://github.com/coin-or/pulp/issues/231)
- the CLI is now a bit of a jungle
- further checking of datatypes and better error messages
> Convert an OSeMOSYS datafile into a Tabular Data Package

- setup.cfg
- src/otoole/__init__.py
- src/otoole/cli.py
- src/otoole/validate.py
- src/otoole/validate.yaml
- src/otoole/visualise/res.py
- tests/test_validate.py
- tests/travis_install.sh
Partial solution to #12 
- Validates the naming codes used in the `technology` and `fuel` tables in a Tabular Data Package against an internally specified validation config file
To do:
Prints out the following for [v1.0a](https://github.com/OSeMOSYS/simplicity/archive/v0.1a0.zip) of the Simplicity model:
```
***Beginning validation***
***Checking TECHNOLOGY names***
29 invalid names:
BACKSTOP1, BACKSTOP2, BIOMASSPRO, CHP, ETHPLANT, ELEC_IMPORT, GAS_EXTRACTION, GAS_IMPORT, GRID_EXP, HYD1, HYD2, IMPDSL, IMPFERT, IMPRAWSUG, LNDFORCOV, LNDRES, LNDSUGPL, LNDSUGPLIR, LNDSUGPLRF, NGCC, RIVER, RIVER_2, RIVWATAGR, SOLPV1, SOLPV2, SUGFACTORY, TD, TD2, WINDPOWER
***Checking FUEL names***
21 invalid names:
BAGASSE, BIOMASS, DSL, ETH, FEL1, FEL2, FER, GAS, HEAT, LAND, LANDFOREST, LNDSUGCAN, MOLASSES, …
```
> Adds a validate function to the command line interface

- src/otoole/validate.py
- src/otoole/validate.yaml
- src/otoole/visualise/res.py
- tests/test_validate.py
Allows OSeMOSYS resources (e.g. sets such as TECHNOLOGY, FUEL, EMISSION) to be validated using multiple expressions defined in a YAML configuration file.
> Validate resources using multiple expressions

- requirements.txt
- src/otoole/preprocess/config.yaml
- src/otoole/preprocess/create_datapackage.py
- src/otoole/preprocess/datafile_to_datapackage.py
- src/otoole/preprocess/datapackage.json
- src/otoole/preprocess/longify_data.py
- src/otoole/preprocess/narrow_to_datafile.py
Upon converting to a datapackage, otoole now writes the default values for parameters into the datapackage as `default_values.csv`.
Bug #36 was caused by the erroneous use of "missing values", which replaced all values that matched the list of missing values with `N/A`. These were then omitted when writing back out to the datafile.
This pull request removes the use of the missingvalues field, and instead stores the default values in a separate csv file in the datapackage.
> Fix for #36

- src/otoole/input.py
- src/otoole/read_strategies.py
- tests/test_read_strategies.py
Adds a `ReadMemory` class to the read strategies module to ease programmatic use of otoole when a user already has the OSeMOSYS parameters available in memory.
> Read a dict of parameters from memory

- src/otoole/input.py
- src/otoole/read_strategies.py
- src/otoole/results/convert.py
- src/otoole/results/result_package.py
- tests/results/test_results_package.py
- tests/test_read_strategies.py
* Fixes an issue with ReadStrategies not setting indexes on the
dataframes (#62)
* Results processing requires indexes to be set to compute results
> Lack of indexes on dataframe break results

- src/otoole/exceptions.py
- src/otoole/read_strategies.py
- src/otoole/utils.py
- src/otoole/write_strategies.py
- tests/fixtures/config.yaml
- tests/test_utils.py
**OVERVIEW**
This PR adds a `short_name` value to the `config.yaml` which will overwrite the full parameter name when writing user defined parameters to an excel file. 
**LOGIC**
Adds a new utility function called `create_name_mappings( ... )` which will create a mapping dictionary similar to the previous `EXCEL_TO_CSV` hard coded dictionary. This function is called in the `ReadExcel` class only. When writing to excel, the logic just checks if there is a `short_name` value associated with the parameter or not, and writes that out. 
**QUESTIONS**
1.  The downside of only calling `create_name_mappings( ... )` when reading is that we do not log to the user if their parameter name is longer then 31 characters. I guess my justification for doing this is I tried to keep the logging within the …
> Long parameter names cause an error in writing to an Excel spreadsheet

- src/otoole/cli.py
- src/otoole/input.py
- src/otoole/read_strategies.py
- src/otoole/write_strategies.py
- tests/test_input.py
- tests/test_read_strategies.py
- tests/test_write_strategies.py
Hello! 
In this PR I implement logic in the `ReadExcel` class to create empty dataframes for parameters that do not have an associated excel sheet. This PR relates to issue #99, and [this comment](https://github.com/OSeMOSYS/otoole/issues/114#issuecomment-1358393751) in issue #114. 
I was reviewing issue #99 and encountered a very similar issue to the one described. When we convert from anything to an Excel file, only parameters that have non-default values are written. For example, in Simplicity the DiscountRate is given by a default value, therefore, no `DiscountRate` sheet will appear after running the command `otoole convert <> excel <> params.xlsx config.yaml`. 
In a different [comment](https://github.com/OSeMOSYS/otoole/issues/114#issuecomment-1358393751) (see issue #114) I discuss …
> Create missing params when reading from excel 

- src/otoole/read_strategies.py
- src/otoole/write_strategies.py
- tests/test_read_strategies.py
This PR addresses issue #139 and deprecates the reading/writing of `default_values.csv`, as all default values should be defined in the `config.yaml` file. Tests are included for the added logic. 
In the `convert` function, if a folder of csvs is read in and a `default_values.csv` file is found, an `OtooleDeprecationError` is raised that instructs the user to define defaults in the `config.yaml` file. 
If a file called `data/default_values.csv` exists
```bash
(otoole) ~/repositories/otoole/trevor$ otoole convert csv datafile data/ test.txt config.yaml 
OtooleDeprecationError: data/default_values.csv -> Remove default_values.csv and define all default values in the configuration file
```
> Deprecated default_values.csv

- src/otoole/cli.py
- src/otoole/exceptions.py
- src/otoole/preprocess/config.yaml
- src/otoole/preprocess/setup.py
- src/otoole/write_strategies.py
- tests/test_cli.py
- tests/test_setup.py
In this PR I have added `setup` functionality to create a template user configuration file and template CSV files. If the user tries to create the template file(s) and an existing version already exists, they must pass an `--overwrite` flag. This prevents the accidental overwrite of data that is not backed up! Tests have been added for the new functionality. 
Completes one of the tasks in issue #56 
```bash
(otoole) ~/repositories/otoole$ otoole setup --help
usage: otoole setup [-h] [--write_defaults] [--overwrite] {config,csv} data_path
positional arguments:
{config,csv}      Type of file to setup
data_path         Path to file or folder to save to
optional arguments:
-h, --help        show this help message and exit
--write_defaults  Writes default values
--overwrite       Overwrites …
```
> Add `otoole setup` commands

- src/otoole/cli.py
- src/otoole/input.py
- src/otoole/write_strategies.py
In this PR I fix a bug that caused the excel column names not to be written out if the dataframe is empty. 
The issue was that we were passing over the entire dataframe if no input data was found, rather then passing over only the pivoting of the years logic if no input data is found.
> Excel template headers bug

- src/otoole/cli.py
- src/otoole/read_strategies.py
- tests/test_read_strategies.py
**THIS IS A DRAFT PR** 
Hi! I was chatting with @tniet the other day about a workflow that is breaking due to whitespace in a CSV file (see example below). We quickly discussed using `otoole` to strip out whitespace when writing to the datafile. However, thinking about this solution a little more, Im not sure this functionality should be included in `otoole`. 
When whitespace is included in the input data, `otoole` still behaves as expected; it converts the data without raising an error. If we start using otoole to format input data (even just striping out whitespace), this seems outside `otoole`'s scope of work - which my understanding is just data conversion, data visualizaion, and data validation through a config file.
With that said, I have pushed a quick (draft) fix of what a …
> Whitespace removal on reading in of data 

- src/otoole/preprocess/config.yaml
Remove the `DiscountRateIdv` value from the template configuration file, as this is just assigned to the same value as the `DiscountRate` parameter in the current OSeMOSYS versions. The user can add this parameter into the config file if they want custom `DiscountRateIdv` values
> Update config template

- requirements.txt
- setup.cfg
With the recent release of `pandas 2.0`, some tests in otoole are failing. Seems like the failing tests are caused by some regular expressions and data type inconsistencies. Constraining pandas to `pandas<2.0` (which results in installing `pandas 1.5.3`) all tests work fine.
> Downgrade Pandas 

- src/otoole/exceptions.py
- src/otoole/input.py
Improves error reporting when there are multiple mismatches between data and config.
Modified the `OtooleNameMismatchError` to better handle lists of names.
None
None
> Minor typos and improved error message for multiple names

- src/otoole/input.py
- tests/test_input.py
Adds a `try` `except` block to check for the exception `ValueError: invalid literal for int() with base 10:` when type casting the set indices upon reading in data. This error is raised when trying to cast a column from a `float` to an `int`. If the error is raised, the entire column is first cast as a float, then in turn cast as an int. This seems to be the normal way to deal with this error according to [stack overflow](https://stackoverflow.com/a/49088974). 
Tests for the `ReadStrategy._check_index_dtypes(..)` have been expanded to check for more datatypes as well. Previously they only tested for string->X type casting. (My bad for that 😅)
I would not exactly call this an elegant solution, since each column needs to be cast one by one if the `except` logic is entered. But this is a bit …
> Updates dtype casting when reading in data 

- src/otoole/write_strategies.py
- tests/test_write_strategies.py
In this PR I have fixed the issue of `WriteExcel._form_parameter(..)` pivoting data that is not indexed over years. An accompanying test is added for the new logic. 
Closes #171 
na
> Excel pivoting bug fix

- docs/data.rst
- docs/requirements.txt
`urllib3` recently updated to version `2` which is causing some errors with Sphinx (see the build [here](https://readthedocs.org/projects/otoole/builds/20373882/)). urllib3 community suggested locking urllib3 to `<2` until a fix is pushed. 
na
na
> Docs build fix for v1.0.3

- docs/requirements.txt
- setup.cfg
- src/otoole/preprocess/validate_config.py
**DRAFT PR**
In this PR I update the configuration file validation logic to work with `pydantic>=2.0`, following the [Pydantic Migration Guide](https://docs.pydantic.dev/latest/migration/). This is labelled as a draft right now because, while all the tests pass, I think there are a couple additional features we can add. For example, making better use of the [`FieldValidationInfo`](https://docs.pydantic.dev/latest/usage/validators/) and [`ValidationError`](https://docs.pydantic.dev/dev-v2/errors/validation_errors/). I will address this shortly. 
Closes #185 
Na. No changes for the user
> Update to pydantic 2

- docs/functionality.rst
Removes a warning box in the documentation stating the user must sort cplex solution files. This is no longer needed after PR #190 
closes #195 
Functionality page on processing results
> Fixes CPEX result processing docs 

- .github/workflows/python.yaml
- src/otoole/input.py
- src/otoole/results/result_package.py
- src/otoole/results/results.py
- src/otoole/write_strategies.py
- tests/test_cli.py
- tests/test_convert.py
- tests/test_read_strategies.py
- tests/test_utils.py
- tests/test_write_strategies.py
In this PR I update `otoole` to fix failing tests on Windows.
Specifically this includes: 
- Explicitly setting all `int` as `int64` data types when the config file is first read in. Im not sure why, but on Windows pandas seems to set `int` as `int32`, while on Linux it will set it as `int64` (or is just not concerned about `int32` vs. `int64)`. Anyways, `int64` is explicitly set now 
- Explicitly setting `int64` for `int` datatypes in the results package (note, the config file dtypes are not accessible here) 
- Explicitly setting `int64` for `read_strategies` of solvers 
- Specify the `lineterminator` argument as `\n` when writing to csv or datafiles, as Windows will default to `\r\n`. More information [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)
- …
> Fix Tests on Windows 

- CHANGELOG.rst
- docs/requirements.txt
- setup.cfg
- src/otoole/input.py
- tests/test_input.py
Resolves the failing tests which were caused by a regression in version 2.1.0 of pandas.
I ran tests for Python 3.9 and pandas v2.1.0 through v2.1.4. All tests pass for the latest version (v2.1.4) of pandas.
The version pin has been updated to force use of pandas 2.1.4 and later.
Also, a future deprecation issue was resolved.
Closes #194
> Regression in tests caused by pandas fixed by pandas 2.1.4

- CHANGELOG.rst
- src/otoole/results/result_package.py
- tests/results/test_results_package.py
Ensures that CapitalInvestment is calculated using either a DiscountRate or DiscountRateIdv parameter.
Modified the crf() function so that it calculates the capital recovery factor by region and technology using either a technology independent or technology specific discount rate.
Resolves #197 
No additional documentation provided.
> Calculate CapitalInvestment using discount rate with/without technology index

- .pre-commit-config.yaml
- src/otoole/convert.py
- src/otoole/read_strategies.py
- src/otoole/utils.py
- src/otoole/validate.py
In this PR I have upgraded pre-commit to use mypy 1.9.0! 
As part of this process, mypy now prohibits implicit Optional arguments (as described by PEP 484 [here](https://peps.python.org/pep-0484/#union-types)). I have updated the code to add `Optional` type hints where required. Shoutout to[ this repo](https://github.com/hauntsaninja/no_implicit_optional) for having good docs on this issue! (Although I just did the updates manually, rather than use their package, since there were only a few places where this was an issue) 
Closes #222 
na
> Upgrade to mypy 1.9.0

- docs/examples.rst
- docs/functionality.rst
Added instructions to install graphviz under `docs/functionality.rst`.
I have just added few sentences in the documentation to flag the need for gaphviz to be installed, if the user wants to use the `otoole viz` functionality.
No issue raised.
`docs/functionality.rst`
> Added instructions to install graphviz, if needed.

- .github/workflows/python.yaml
- CHANGELOG.rst
- README.rst
- src/otoole/input.py
In This PR I add testing support for Python 3.12
Closes #212
na
> Add Python 3.12 support 

- src/otoole/results/result_package.py
- src/otoole/results/results.py
- tests/conftest.py
- tests/results/test_results_package.py
- tests/test_read_strategies.py
In this PR I have addressed the failing CRF calculation if no discount rate is provided (which was partially addressed in PR #216). Following @willu47's suggestion in ticket #217, the `_expand_default()` function is used to ensure discount rate data is always passed into the CRF, PVA, and Discount Factor functions. Since handling the `DiscountRate` and `DiscountRateIdv` differences is a little confusing (imo), I also added in `ValueError` checks to the functions to check for non-empty discount rates - but these shouldnt really be needed. Just added as double check. 
closes #217 
na
> Correct CRF calcualtions for empty discount rates 

- src/otoole/results/result_package.py
- tests/conftest.py
- tests/results/test_results_package.py
In this PR I have corrected how `DiscountRate` and `DiscountRateIdv` are used in the `CapitalInvestment` calculation. Specifically, the logic has been updated so: 
- If `DiscountRateIdv` is not found in input data, or is empty, the calculation will fall back to using `DiscountRate`. This addresses issue #220
- If `DiscountRateIdv` is found in input data, and has values, the calculation will pass `DiscountRateIdv` to the CRF calculation, and `DiscountRate` to the PVA calculation. This addresses #228
A test called `TestCapitalInvestment` has been added to test this logic. Also, the `DicountRateIdv` fixture was update so its values are different from the `DiscountRate` fixture. 
Closes #220 
Closes #228
na
> Fix `CapitalInvestment` result calculation 

- CHANGELOG.rst
- src/otoole/preprocess/config.yaml
- src/otoole/results/result_package.py
- tests/results/test_results_package.py
I have an application where I want to use the `DiscountedCostByTechnology` result variable. However, `otoole` does this calculation internally within the `TotalDiscountedCost` calculation, and does not print out this data. This PR addresses this. 
Specifically, in this PR I have: 
- Broken out the calculations for `DiscountedCapitalInvestment`, `DiscountedCostByTechnology`, and `DiscountedOperationalCost` into separate functions. When results are calculated, dataframes for each of these are generated, which can be written out in csvs or xlsx. 
- Functions that rely on this data (such as `TotalDiscountedCost`), now use these intermediate dataframes to perform the calculation. This simplifies the `TotalDiscountedCost` result calculation quite a bit. 
- Tests for each of …
> Add discounted result calcualtions 

- CHANGELOG.rst
- src/otoole/preprocess/config.yaml
- src/otoole/results/result_package.py
- tests/results/test_results_package.py
In this PR I have updated the objective cost calculation to account for storage costs. Additionally, I have added result calculations for non-discounted storage investment costs, discounted storage investment costs, discounted storage salvage value, and total discounted cost by storage. 
Closes #237 
na
> Update Objective Cost Calculation 
